### ISSUE TITLE
SidebarIssue not creating any comments during CI pull request scan

### ISSUE THREAD

**Issue by SujithCheruvilKaizen** [AikidoSec/github-actions-workflow#52]
During Aikido CI scan for a pull request from the main branch of repository to another branch, it failed with few sidebar issues.

![image](https://github.com/AikidoSec/github-actions-workflow/assets/127106402/5847830f-0eea-4d59-bffb-69a5297f986a)

`Error: New issue detected with severity >=HIGH. Check it out at: https://app.aikido.dev/queue?sidebarIssue=772217`

The link takes to the issue which was already raised in Aikido dashboard. And there are no comments on the PR from Aikido with description of the issue.

Is there a way to enable descriptive comments on the issues? Or a way to fail the scan only if issues related to the file changes in the PR are found?

```yaml
- name: Aikido scan
  id: aikido_scan
  uses: AikidoSec/github-actions-workflow@v1.0.13
  continue-on-error: true
  with:
    secret-key: ${{ secrets.AIKIDO_SECRET_KEY }}
    fail-on-timeout: true
    fail-on-dependency-scan: true
    fail-on-sast-scan: true
    fail-on-iac-scan: true
    minimum-severity: "HIGH"
    timeout-seconds: 180
    post-scan-status-comment: "only_if_new_findings"
    post-sast-review-comments: "on"
    github-token: ${{ secrets.GITHUB_TOKEN }}
```
